apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    helm.sh/chart: awx-operator-0.30.0
  name: awx-operator-controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
    helm.sh/chart: awx-operator-0.30.0
