---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options: {}
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: test-minikube
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        operator_namespace: ${TEST_NAMESPACE:-default}
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - destroy
