---

- name: Emit ocp event with error
  operator_sdk.util.k8s_event:
    state: present
    name: restore-error
    namespace: "{{ ansible_operator_meta.namespace }}"
    reason: RestoreFailed
    message: "{{ error_msg }}"
    type: Warning
    involvedObject:
      apiVersion: "{{ api_version }}"
      kind: "{{ kind }}"
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ ansible_operator_meta.namespace }}"
