---

- name: Determine the timestamp
  set_fact:
    now: '{{ lookup("pipe", "date +%FT%TZ") }}'

- name: Emit ocp event with error
  kubernetes.core.k8s:
    kind: Event
    namespace: "{{ ansible_operator_meta.namespace }}"
    definition: "{{ lookup('template', 'event.yml.j2') }}"
