---

- name: Import awx_object variables
  block:
  - name: Get AWX object definition from pvc
    kubernetes.core.k8s_exec:
      namespace: "{{ backup_pvc_namespace }}"
      pod: "{{ ansible_operator_meta.name }}-db-management"
      command: >-
        bash -c "cat '{{ backup_dir }}/awx_object'"
    register: awx_object

  - name: Create temp file for spec dict
    ansible.builtin.tempfile:
      state: file
    register: tmp_spec

  - name: Write spec vars to temp file
    ansible.builtin.copy:
      content: "{{ awx_object.stdout }}"
      dest: "{{ tmp_spec.path }}"
      mode: '0644'

  - name: Include spec vars to save them as a dict
    ansible.builtin.include_vars: "{{ tmp_spec.path }}"
