---

- name: Update CR Restore status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      restoreComplete: true
      restorePostgres: "{{ not postgres_skip_data | bool or awx_postgres_type == 'managed' }}"
  when: tower_restore_complete is defined
