# permissions for end users to edit awxmeshingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awxmeshingress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: awx-operator
    app.kubernetes.io/part-of: awx-operator
    app.kubernetes.io/managed-by: kustomize
  name: awxmeshingress-editor-role
rules:
- apiGroups:
  - awx.ansible.com
  resources:
  - awxmeshingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - awx.ansible.com
  resources:
  - awxmeshingresses/status
  verbs:
  - get
