apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      
resources:
  - awx_editor_role.yaml
  - awxbackup_editor_role.yaml
  - awxmeshingress_editor_role.yaml
  - awxrestore_editor_role.yaml