# TODO: Add tests for AWXMeshIngress
# ---
# - name: Create the awx.ansible.com/v1alpha1.AWXMeshIngress
#   k8s:
#     state: present
#     namespace: '{{ namespace }}'
#     definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
#     wait: yes
#     wait_timeout: 300
#     wait_condition:
#       type: Successful
#       status: "True"
#   vars:
#     cr_file: 'awx_v1alpha1_awxmeshingress.yaml'

# - name: Add assertions here
#   assert:
#     that: false
#     fail_msg: FIXME Add real assertions for your operator
