apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-operator-awx-manager-config
data:
  controller_manager_config.yaml: |
    ---
    apiVersion: controller-runtime.sigs.k8s.io/v1beta1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :6789
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: 811c9dc5.ansible.com
