apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-operator-awx-manager-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-operator-awx-manager-role
subjects:
- kind: ServiceAccount
  name: awx-operator-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: awx-operator-controller-manager
  namespace: {{ .Release.Namespace }}
