# permissions for end users to view awxbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awxbackup-viewer-role
rules:
- apiGroups:
  - awx.ansible.com
  resources:
  - awxbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awx.ansible.com
  resources:
  - awxbackups/status
  verbs:
  - get
