---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Build operator image
      docker_image:
        build:
          path: '{{ project_dir }}'
          pull: no
          args:
            DEFAULT_AWX_VERSION: '{{ default_awx_version }}'
        name: '{{ operator_image }}'
        tag: latest
        push: no
        source: build
        force_source: yes

    - name: Load operator image into kind cluster
      command: kind load docker-image --name osdk-test '{{ operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'

    - name: Load awx image into kind cluster
      command: kind load docker-image --name osdk-test '{{ awx_image }}:{{ awx_version }}'
      register: result
      changed_when: '"not yet present" in result.stdout'
      when:
        - awx_image is defined
        - awx_image != ''

- import_playbook: ../default/converge.yml
