---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    # Remove after this if fixed: https://github.com/ansible-collections/community.docker/issues/611
    - name: Install docker
      become: yes
      pip:
        name:
          - websocket-client==0.59.0
          - requests==2.28.2
          - urllib3==1.26.15
          - docker
          - docker-compose
        state: present

    - name: Build operator image
      community.docker.docker_image:
        build:
          path: '{{ project_dir }}'
          pull: no
          args:
            DEFAULT_AWX_VERSION: '{{ default_awx_version }}'
        name: '{{ operator_image }}'
        tag: latest
        push: no
        source: build
        force_source: yes

    - name: Load operator image into kind cluster
      command: kind load docker-image --name osdk-test '{{ operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'

    - name: Load awx image into kind cluster
      command: kind load docker-image --name osdk-test '{{ awx_image }}:{{ awx_version }}'
      register: result
      changed_when: '"not yet present" in result.stdout'
      when:
        - awx_image is defined
        - awx_image != ''

- import_playbook: ../default/converge.yml
