---
# Check to make sure provided pvc exists, error loudly if not.  Otherwise, the management pod will just stay in pending state forever.
- name: Check provided PVC claim exists
  kubernetes.core.k8s_info:
    name: "{{ _metrics_utility_pvc_claim }}"
    kind: PersistentVolumeClaim
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: provided_pvc
  when:
    - _metrics_utility_pvc_claim | length

- block:
    - name: Create PVC for metrics-utility
      kubernetes.core.k8s:
        kind: PersistentVolumeClaim
        definition: "{{ lookup('template', 'storage/metrics-utility.yaml.j2') }}"

- block: 
    - name: Create Kubernetes CronJob for metrics-utility-gather
      kubernetes.core.k8s:
        name: "{{ ansible_operator_meta.name }}-metrics-utility-gather"
        kind: CronJob
        definition: "{{ lookup('template', 'cronjobs/metrics-utility-gather.yaml.j2') }}"
        wait: true

- block: 
    - name: Create Kubernetes CronJob for metrics-utility-report
      kubernetes.core.k8s:
        name: "{{ ansible_operator_meta.name }}-metrics-utility-report"
        kind: CronJob
        definition: "{{ lookup('template', 'cronjobs/metrics-utility-report.yaml.j2') }}"
        wait: true