---
# Check to make sure provided pvc exists, error loudly if not.  Otherwise, the management pod will just stay in pending state forever.
- name: Check provided PVC claim exists
  kubernetes.core.k8s_info:
    name: "{{ _metrics_utility_pvc_claim }}"
    kind: PersistentVolumeClaim
    namespace: "{{ ansible_operator_meta.namespace }}"
  when:
    - _metrics_utility_pvc_claim | length

- name: Create PVC for metrics-utility
  kubernetes.core.k8s:
    kind: PersistentVolumeClaim
    definition: "{{ lookup('template', 'storage/metrics-utility.yaml.j2') }}"

- name: Create Kubernetes CronJobs for metrics-utility
  kubernetes.core.k8s:
    definition: "{{ lookup('template', item) }}"
    apply: true
    wait: true
  loop:
    - cronjobs/metrics-utility-gather.yaml.j2
    - cronjobs/metrics-utility-report.yaml.j2
