---
# Check to make sure provided pvc exists, error loudly if not.  Otherwise, the management pod will just stay in pending state forever.
- name: Check provided PVC claim exists
  kubernetes.core.k8s_info:
    name: "{{ _metrics_pvc_claim }}"
    kind: PersistentVolumeClaim
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: provided_pvc
  when:
    - _metrics_pvc_claim | length

- block:
    - name: Create PVC for metrics
      kubernetes.core.k8s:
        kind: PersistentVolumeClaim
        definition: "{{ lookup('template', 'storage/metrics.yaml.j2') }}"

- block: 
    - name: Create Kubernetes CronJob for metrics-gather
      kubernetes.core.k8s:
        name: "{{ ansible_operator_meta.name }}-metrics-gather"
        kind: CronJob
        definition: "{{ lookup('template', 'cronjobs/metrics-gather.yaml.j2') }}"
        wait: true

- block: 
    - name: Create Kubernetes CronJob for metrics-report
      kubernetes.core.k8s:
        name: "{{ ansible_operator_meta.name }}-metrics-report"
        kind: CronJob
        definition: "{{ lookup('template', 'cronjobs/metrics-report.yaml.j2') }}"
        wait: true