---
- name: Retrieve LDAP CA Certificate Secret
  community.kubernetes.k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ ldap_cacert_secret }}'
  register: ldap_cacert

- name: Load LDAP CA Certificate Secret content
  set_fact:
    ldap_cacert_ca_crt: '{{ ldap_cacert["resources"][0]["data"]["ldap-ca.crt"] | b64decode }}'
  when: '"ldap-ca.crt" in ldap_cacert["resources"][0]["data"]'
