---
- name: Retrieve bundle Certificate Authority Secret
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ bundle_cacert_secret }}'
  register: bundle_cacert
  no_log: "{{ no_log }}"

- name: Load bundle Certificate Authority Secret content
  set_fact:
    bundle_ca_crt: '{{ bundle_cacert["resources"][0]["data"]["bundle-ca.crt"] | b64decode }}'
  no_log: "{{ no_log }}"
  when: '"bundle-ca.crt" in bundle_cacert["resources"][0]["data"]'
