---
- name: Patch default pull secret to operator ServiceAccount (Upstream)
  block:
    - name: Check for existing operator SA
      k8s_info:
        kind: ServiceAccount
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ _sa_prefix }}-controller-manager'
      vars:
        _sa_prefix: awx-operator
      register: _sa_exists
      no_log: true

    - name: Patch SA with image pull secret default
      k8s:
        apply: yes
        definition: "{{ lookup('template', 'patch_operator_service_account.yml') }}"
        wait: yes
      vars:
        _sa_prefix: awx-operator
      when: _sa_exists['resources'] | length

- name: Patch default pull secret to operator ServiceAccount (Downstream)
  block:
    - name: Check for existing operator SA
      k8s_info:
        kind: ServiceAccount
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ _sa_prefix }}-controller-manager'
      vars:
        _sa_prefix: automation-controller-operator
      register: _sa_exists
      no_log: true

    - name: Patch SA with image pull secret default
      k8s:
        apply: yes
        definition: "{{ lookup('template', 'patch_operator_service_account.yml') }}"
        wait: yes
      vars:
        _sa_prefix: automation-controller-operator
      when: _sa_exists['resources'] | length
