apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: example-awx-backup
spec:
  deployment_name: example-awx
  backup_resource_requirements:
    limits:
      cpu: "1000m"
      memory: "4096Mi"
    requests:
      cpu: "25m"
      memory: "32Mi"
