---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:
    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
      tags:
        - always

    - import_tasks: kustomize.yml
      vars:
        state: present
      tags:
        - always
