---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'

    - name: Run kustomize tasks
      ansible.builtin.import_tasks: tasks/kustomize.yml
      vars:
        state: present
