---
- name: Build kustomize testing overlay
  # load-restrictor must be set to none so we can load patch files from the default overlay
  command: '{{ kustomize }} build  --load-restrictor LoadRestrictionsNone .'
  args:
    chdir: '{{ config_dir }}/testing'
  register: resources
  changed_when: false
  tags:
    - always

- name: Set resources to {{ state }}
  k8s:
    definition: '{{ item }}'
    state: '{{ state }}'
    wait: yes
  loop: '{{ resources.stdout | from_yaml_all | list }}'
  tags:
    - always
