---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core

  vars:
    ctrl_label: control-plane=controller-manager

  tasks:
    - name: Perform awx tests
      block:
        - name: Import all test files from tasks/
          ansible.builtin.include_tasks: '{{ item }}'
          with_fileglob:
            - tasks/awx_test.yml
            - tasks/awx_replicas_test.yml
          tags:
            - always
      rescue:
        - name: Create debug output directory
          ansible.builtin.file:
            path: '{{ debug_output_dir }}'
            state: directory
          tags:
            - always

        - name: Gather and output K8s resources
          ansible.builtin.include_tasks: utils/output_k8s_resources.yml
          tags:
            - always

        - name: Get all pods
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Pod
            namespace: '{{ namespace }}'
          register: all_pods
          tags:
            - always

        - name: Get all container logs for all pods
          ansible.builtin.include_tasks: utils/output_all_container_logs_for_pod.yml
          loop: '{{ all_pods.resources }}'
          ignore_errors: yes
          tags:
            - always

        - name: Re-emit failure
          vars:
            failed_task:
              result: '{{ ansible_failed_result }}'
          ansible.builtin.fail:
            msg: '{{ failed_task }}'
          tags:
            - always
