{{- if and (not $.Values.AWX.postgres.enabled) (eq (($.Values.AWX.spec).postgres_configuration_secret | default "") "") -}}
{{- if (($.Values.customVolumes).postgres).enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.persistentVolumeName" $ }}
{{- with $.Values.customVolumes.postgres }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .accessModes }}
  persistentVolumeReclaimPolicy: {{ default "Retain" .reclaimPolicy | quote }}
  capacity:
    storage: {{ default "8Gi" .size | quote }}
  storageClassName: {{ include "postgres.storageClassName" $ }}
  hostPath:
    path: /var/lib/pgsql/data/userdata
{{- end }}
{{- end }}
{{- end }}
