---
galaxy_info:
  author: Ansible
  description: AWX role for AWX Operator for Kubernetes.
  company: Red Hat, Inc.

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - tower
    - controller
    - awx
    - ansible
    - restore
    - automation

dependencies:
  - role: common

collections:
  - kubernetes.core
  - operator_sdk.util
