---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: nodeport
  admin_user: admin1
  image: quay.io/ansible/awx
  image_version: 19.5.1
  image_pull_policy: Always
  control_plane_ee_image: quay.io/ansible/awx-ee:latest
  redis_image: redis
  redis_image_version: "6.2.6-bullseye"
  postgres_image: postgres
  postgres_image_version: "12"
  postgres_resource_requirements:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 4Gi
  postgres_storage_requirements:
    requests:
      storage: 3Gi
    limits:
      storage: 8Gi
  postgres_storage_class: standard
  postgres_extra_args:
    - '-c'
    - 'max_connections=1000'
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  ee_resource_requirements:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-admin-password
  namespace: awx
stringData:
  password: "admin1234"
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-postgres-configuration
  namespace: awx
stringData:
  host: "awx-demo-postgres"
  port: "5432"
  database: "awx"
  username: "awx2"
  password: "awx12345"
  sslmode: "prefer"
  type: "managed"
type: Opaque