# permissions for end users to view awxs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-viewer-role
rules:
- apiGroups:
  - awx.ansible.com
  resources:
  - awxs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awx.ansible.com
  resources:
  - awxs/status
  verbs:
  - get
