# permissions for end users to view awxmeshingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awxmeshingress-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: awx-operator
    app.kubernetes.io/part-of: awx-operator
    app.kubernetes.io/managed-by: kustomize
  name: awxmeshingress-viewer-role
rules:
- apiGroups:
  - awx.ansible.com
  resources:
  - awxmeshingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awx.ansible.com
  resources:
  - awxmeshingresses/status
  verbs:
  - get
