---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awxmeshingresses.awx.ansible.com
spec:
  group: awx.ansible.com
  names:
    kind: AWXMeshIngress
    listKind: AWXMeshIngressList
    plural: awxmeshingresses
    singular: awxmeshingress
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AWXMeshIngress is the Schema for the awxmeshingresses API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of AWXMeshIngress
            type: object
            x-kubernetes-preserve-unknown-fields: true
            required:
            - deployment_name
            properties:
              deployment_name:
                description: Name of the AWX deployment to create the Mesh Ingress for.
                type: string
              image_pull_secrets:
                description: Image pull secrets for Mesh Ingress containers.
                type: array
                items:
                  type: string
              external_hostname:
                description: External hostname to use for the Mesh Ingress.
                type: string
              external_ipaddress:
                description: External IP address to use for the Mesh Ingress.
                type: string
              ingress_type:
                description: The ingress type to use to reach the deployed instance
                type: string
                enum:
                - none
                - Ingress
                - ingress
                - IngressRouteTCP
                - ingressroutetcp
                - Route
                - route
              ingress_api_version:
                description: The Ingress API version to use
                type: string
              ingress_annotations:
                description: Annotations to add to the Ingress Controller
                type: string
              ingress_class_name:
                description: The name of ingress class to use instead of the cluster default.
                type: string
              ingress_controller:
                description: Special configuration for specific Ingress Controllers
                type: string
          status:
            description: Status defines the observed state of AWXMeshIngress
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
