---

name: CI

on:
  pull_request:
  push:

jobs:
  molecule:
    runs-on: ubuntu-latest
    name: molecule
    strategy:
      matrix:
        ansible_args:
          - --skip-tags=replicas
          - -t replicas
    env:
      DOCKER_API_VERSION: "1.44"
      DEBUG_OUTPUT_DIR: /tmp/awx_operator_molecule_test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r molecule/requirements.txt

      - name: Install Collections
        run: |
          ansible-galaxy collection install -r molecule/requirements.yml

      - name: Run Molecule
        env:
          MOLECULE_VERBOSITY: 3
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          STORE_DEBUG_OUTPUT: true
        run: |
          sudo rm -f $(which kustomize)
          make kustomize
          KUSTOMIZE_PATH=$(readlink -f bin/kustomize) molecule test -s kind -- ${{ matrix.ansible_args }}

      - name: Upload artifacts for failed tests if Run Molecule fails
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: awx_operator_molecule_test
          path: ${{ env.DEBUG_OUTPUT_DIR }}
  no-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check no_log statements
        run: |
          set +e
          no_log=$(grep -nr ' no_log:' roles | grep -v '"{{ no_log }}"')
          if [ -n "${no_log}" ]; then
            echo 'Please update the following no_log statement(s) with the "{{ no_log }}" value'
            echo "${no_log}"
            exit 1
          fi
  nox-sessions:
    uses: ./.github/workflows/reusable-nox.yml
