---

name: Devel

on:
  push:
    branches: [devel]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push devel image
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Fail if QUAY_REGISTRY not set
        run: |
          if [[ -z "${{ vars.QUAY_REGISTRY }}" ]]; then
            echo "QUAY_REGISTRY not set. Please set QUAY_REGISTRY in variable GitHub Actions variables."
            exit 1
          fi

      - name: Log into registry ghcr.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f    # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Log into registry quay.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f    # v4.6.0
        with:
          registry: ${{ vars.QUAY_REGISTRY }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}


      - name: Build and Store Image @ghcr
        run: |
          IMG=ghcr.io/${{ github.repository }}:${{ github.sha }} make docker-buildx


      - name: Publish Image to quay.io
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --tag ${{ vars.QUAY_REGISTRY }}/awx-operator:devel
