name: Label PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  community:
    runs-on: ubuntu-latest
    name: Label PR - Community
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Create a virtual environment
        run: python3 -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip3 install requests

      - name: Check if user is a member of Ansible org
        uses: jannekem/run-python-script-action@v1
        id: check_user
        with:
          script: |
            import requests
            headers = {'Accept': 'application/vnd.github+json', 'Authorization': 'token ${{ secrets.GITHUB_TOKEN }}'}
            response = requests.get('${{ fromJson(toJson(github.event.pull_request.user.url)) }}/orgs?per_page=100', headers=headers)
            is_member = False
            for org in response.json():
              if org['login'] == 'ansible':
                is_member = True
            if is_member:
                print("User is member")
            else:
                print("User is community")

      - name: Add community label if not a member
        if: contains(steps.check_user.outputs.stdout, 'community')
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "community"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
