---

name: CI-manual

on:
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-18.04
    name: pull_request
    env:
      DOCKER_API_VERSION: "1.38"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install \
            molecule \
            molecule-docker \
            yamllint \
            ansible-lint \
            openshift \
            jmespath \
            ansible

      - name: Install Collections
        run: |
         ansible-galaxy collection install community.kubernetes operator_sdk.util

      - name: Run Molecule
        env:
          MOLECULE_VERBOSITY: 3
        run: |
          molecule test -s core 
