---
name: Translate Readme

on:
  push:
    branches: [devel]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding License
        uses: dephraiim/translate-readme@v1
        with:
          LANG: fr #French
